title: Lash-L Github pages
theme: just-the-docs
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - FINE_TUNING.md
  - FIRMWARE_UPDATE.md
  - PRINTER_PARTS.md
  - PRINTER_SPECIFICATION.md
  - PRINTER_UPGRADES.md
  - REMOTE_MANAGEMENT.md
  - TROUBLESHOOTING.md
 
remote_theme: pmarsceill/just-the-docs
